'use client';


export const departments = [
  "Bilgisayar Mühendisliği",
  "Elektrik-Elektronik Mühendisliği",
  "Makine Mühendisliği",
  "İnşaat Mühendisliği",
  "Endüstri Mühendisliği",
  "Mimarlık",
  "Tıp",
  "Diş Hekimliği",
  "Eczacılık",
  "Hukuk",
  "İktisat",
  "İşletme",
  "Uluslararası İlişkiler",
  "Psikoloji",
  "Sosyoloji",
  "Tarih",
  "Türk Dili ve Edebiyatı",
  "Fizik",
  "Kimya",
  "Biyoloji",
  "Matematik",
  "İstatistik",
  "Fen Bilgisi Öğretmenliği",
  "İngilizce Öğretmenliği",
  "Rehberlik ve Psikolojik Danışmanlık",
  "Hemşirelik",
  "Fizyoterapi ve Rehabilitasyon",
  "Diyetisyenlik",
  "Gazetecilik",
  "Radyo, Televizyon ve Sinema",
  "İletişim Tasarımı",
  "Grafik Tasarım",
  "Moda Tasarımı",
  "Görsel İletişim Tasarımı",
  "Gastronomi ve Mutfak Sanatları",
  "Müzik",
  "Resim",
  "Heykel",
  "Seramik",
  "Sahne Sanatları",
  "İç Mimarlık",
  "Şehir ve Bölge Planlama",
  "Havacılık ve Uzay Mühendisliği",
  "Jeoloji Mühendisliği",
  "Gıda Mühendisliği",
  "Ziraat Mühendisliği",
  "Veterinerlik",
  "Ormancılık",
  "Su Ürünleri Mühendisliği",
  "Çevre Mühendisliği",
  "Enerji Sistemleri Mühendisliği",
  "Biyomedikal Mühendisliği",
  "Lise Eğitimi"
];
export const universities = [
  "Diğer",
  "Adana Alparslan Türkeş Bilim ve Teknoloji Üniversitesi",
  "Adıyaman Üniversitesi",
  "Afyon Kocatepe Üniversitesi",
  "Ağrı İbrahim Çeçen Üniversitesi",
  "Aksaray Üniversitesi",
  "Alanya Alaaddin Keykubat Üniversitesi",
  "Amasya Üniversitesi",
  "Anadolu Üniversitesi",
  "Ankara Hacı Bayram Veli Üniversitesi",
  "Ankara Sosyal Bilimler Üniversitesi",
  "Ankara Üniversitesi",
  "Ankara Yıldırım Beyazıt Üniversitesi",
  "Ardahan Üniversitesi",
  "Artvin Çoruh Üniversitesi",
  "Atatürk Üniversitesi",
  "Balıkesir Üniversitesi",
  "Bandırma Onyedi Eylül Üniversitesi",
  "Bartın Üniversitesi",
  "Batman Üniversitesi",
  "Bayburt Üniversitesi",
  "Bilecik Şeyh Edebali Üniversitesi",
  "Bingöl Üniversitesi",
  "Bitlis Eren Üniversitesi",
  "Boğaziçi Üniversitesi",
  "Bolu Abant İzzet Baysal Üniversitesi",
  "Burdur Mehmet Akif Ersoy Üniversitesi",
  "Bursa Teknik Üniversitesi",
  "Bursa Uludağ Üniversitesi",
  "Çanakkale Onsekiz Mart Üniversitesi",
  "Çankırı Karatekin Üniversitesi",
  "Çukurova Üniversitesi",
  "Dicle Üniversitesi",
  "Dokuz Eylül Üniversitesi",
  "Düzce Üniversitesi",
  "Ege Üniversitesi",
  "Erciyes Üniversitesi",
  "Erzincan Binali Yıldırım Üniversitesi",
  "Erzurum Teknik Üniversitesi",
  "Eskişehir Osmangazi Üniversitesi",
  "Fırat Üniversitesi",
  "Galatasaray Üniversitesi",
  "Gaziantep Üniversitesi",
  "Gazi Üniversitesi",
  "Gebze Teknik Üniversitesi",
  "Giresun Üniversitesi",
  "Gümüşhane Üniversitesi",
  "Hacettepe Üniversitesi",
  "Hakkari Üniversitesi",
  "Harran Üniversitesi",
  "Hatay Mustafa Kemal Üniversitesi",
  "Hitit Üniversitesi",
  "Iğdır Üniversitesi",
  "Isparta Uygulamalı Bilimler Üniversitesi",
  "İnönü Üniversitesi",
  "İskenderun Teknik Üniversitesi",
  "İstanbul Medeniyet Üniversitesi",
  "İstanbul Teknik Üniversitesi",
  "İstanbul Üniversitesi",
  "İstanbul Üniversitesi-Cerrahpaşa",
  "İzmir Bakırçay Üniversitesi",
  "İzmir Demokrasi Üniversitesi",
  "İzmir Kâtip Çelebi Üniversitesi",
  "Kahramanmaraş İstiklal Üniversitesi",
  "Kahramanmaraş Sütçü İmam Üniversitesi",
  "Karabük Üniversitesi",
  "Karamanoğlu Mehmetbey Üniversitesi",
  "Kastamonu Üniversitesi",
  "Kayseri Üniversitesi",
  "Kırıkkale Üniversitesi",
  "Kırklareli Üniversitesi",
  "Kilis 7 Aralık Üniversitesi",
  "Kocaeli Üniversitesi",
  "Konya Teknik Üniversitesi",
  "Kütahya Dumlupınar Üniversitesi",
  "Kütahya Sağlık Bilimleri Üniversitesi",
  "Malatya Turgut Özal Üniversitesi",
  "Manisa Celal Bayar Üniversitesi",
  "Mardin Artuklu Üniversitesi",
  "Marmara Üniversitesi",
  "Mersin Üniversitesi",
  "Muğla Sıtkı Koçman Üniversitesi",
  "Muş Alparslan Üniversitesi",
  "Nevşehir Hacı Bektaş Veli Üniversitesi",
  "Niğde Ömer Halisdemir Üniversitesi",
  "Ondokuz Mayıs Üniversitesi",
  "Ordu Üniversitesi",
  "Osmaniye Korkut Ata Üniversitesi",
  "Pamukkale Üniversitesi",
  "Recep Tayyip Erdoğan Üniversitesi",
  "Sakarya Uygulamalı Bilimler Üniversitesi",
  "Sakarya Üniversitesi",
  "Samsun Üniversitesi",
  "Siirt Üniversitesi",
  "Sinop Üniversitesi",
  "Sivas Bilim ve Teknoloji Üniversitesi",
  "Sivas Cumhuriyet Üniversitesi",
  "Şırnak Üniversitesi",
  "Süleyman Demirel Üniversitesi",
  "Tarsus Üniversitesi",
  "Tekirdağ Namık Kemal Üniversitesi",
  "Tokat Gaziosmanpaşa Üniversitesi",
  "Trabzon Üniversitesi",
  "Trakya Üniversitesi",
  "Türk-Alman Üniversitesi",
  "Türkiye Enerji, Nükleer ve Maden Araştırma Kurumu (TENMAK) Üniversitesi",
  "Ufuk Üniversitesi",
  "Uşak Üniversitesi",
  "Van Yüzüncü Yıl Üniversitesi",
  "Yalova Üniversitesi",
  "Yozgat Bozok Üniversitesi",
  "Yüksek İhtisas Üniversitesi",
  "Zonguldak Bülent Ecevit Üniversitesi",
  "Atılım Üniversitesi",
  "Bahçeşehir Üniversitesi",
  "Başkent Üniversitesi",
  "Beykent Üniversitesi",
  "Bezmialem Vakıf Üniversitesi",
  "Biruni Üniversitesi",
  "Doğuş Üniversitesi",
  "Fatih Sultan Mehmet Vakıf Üniversitesi",
  "Haliç Üniversitesi",
  "İstanbul Arel Üniversitesi",
  "İstanbul Aydın Üniversitesi",
  "İstanbul Bilgi Üniversitesi",
  "İstanbul Bilim Üniversitesi",
  "İstanbul Gelişim Üniversitesi",
  "İstanbul Kent Üniversitesi",
  "İstanbul Kültür Üniversitesi",
  "İstanbul Medipol Üniversitesi",
  "İstanbul Rumeli Üniversitesi",
  "İstanbul Sabahattin Zaim Üniversitesi",
  "İstinye Üniversitesi",
  "Kadir Has Üniversitesi",
  "Koç Üniversitesi",
  "Maltepe Üniversitesi",
  "MEF Üniversitesi",
  "Nişantaşı Üniversitesi",
  "Özyeğin Üniversitesi",
  "Piri Reis Üniversitesi",
  "Sabancı Üniversitesi",
  "TED Üniversitesi",
  "Toros Üniversitesi",
  "Türk Hava Kurumu Üniversitesi",
  "Üsküdar Üniversitesi",
  "Yaşar Üniversitesi",
  "Yeditepe Üniversitesi"
];
export const highschools = [
  "Diğer",
  "Muğla 75. Yıl Fen Lisesi",
  "İstanbul Erkek Lisesi",
  "Galatasaray Lisesi",
  "Kabataş Erkek Lisesi",
  "Ankara Atatürk Anadolu Lisesi",
  "İzmir Fen Lisesi",
  "İstanbul Atatürk Fen Lisesi",
  "Çapa Fen Lisesi",
  "Ankara Fen Lisesi",
  "Bornova Anadolu Lisesi",
  "Beşiktaş Atatürk Anadolu Lisesi",
  "Kadıköy Anadolu Lisesi",
  "Bursa Fen Lisesi",
  "Vefa Lisesi",
  "Samsun Garip Zeycan Yıldırım Fen Lisesi",
  "İzmir Atatürk Lisesi",
  "Marmara Üniversitesi Fen Lisesi",
  "Koç Üniversitesi Anadolu Lisesi",
  "Robert Koleji",
  "Hisar Okulları",
  "İstanbul Üsküdar Amerikan Lisesi",
  "Tarsus Amerikan Koleji",
  "TED Ankara Koleji",
  "Saint Joseph Fransız Lisesi",
  "Sankt Georg Avusturya Lisesi",
  "Notre Dame de Sion Fransız Lisesi",
  "Sainte Pulcherie Fransız Lisesi",
  "İzmir Özel Türk Koleji",
  "Özel Çevre Fen Lisesi",
  "Özel Eyüboğlu Fen Lisesi",
  "Adana Fen Lisesi",
  "Adıyaman Fen Lisesi",
  "Afyonkarahisar Fen Lisesi",
  "Ağrı Fen Lisesi",
  "Aksaray Fen Lisesi",
  "Amasya Macit Zeren Fen Lisesi",
  "Antalya Yusuf Ziya Öner Fen Lisesi",
  "Ardahan Halil Efendi Fen Lisesi",
  "Artvin Fen Lisesi",
  "Aydın Fen Lisesi",
  "Balıkesir Ali Hikmet Paşa Fen Lisesi",
  "Bartın Fen Lisesi",
  "Batman Fen Lisesi",
  "Bayburt Fen Lisesi",
  "Bilecik Fen Lisesi",
  "Bingöl Fen Lisesi",
  "Bitlis Fen Lisesi",
  "Bolu Fen Lisesi",
  "Burdur Fen Lisesi",
  "Bursa Tofaş Fen Lisesi",
  "Çanakkale Fen Lisesi",
  "Çankırı Fen Lisesi",
  "Çorum Fen Lisesi",
  "Denizli Erbakır Fen Lisesi",
  "Diyarbakır Cumhuriyet Fen Lisesi",
  "Düzce Fen Lisesi",
  "Edirne Fen Lisesi",
  "Elazığ Kaya Karakaya Fen Lisesi",
  "Erzincan Fen Lisesi",
  "Erzurum Fen Lisesi",
  "Eskişehir Fatih Fen Lisesi",
  "Gaziantep Vehbi Dinçerler Fen Lisesi",
  "Giresun Fen Lisesi",
  "Gümüşhane Fen Lisesi",
  "Hakkari Fen Lisesi",
  "Hatay İskenderun Tosçelik Fen Lisesi",
  "Iğdır Fen Lisesi",
  "Isparta Fen Lisesi",
  "Kahramanmaraş Çukurova Elektrik Fen Lisesi",
  "Karabük Mehmet Vergili Fen Lisesi",
  "Karaman Fen Lisesi",
  "Kars Fen Lisesi",
  "Kastamonu Abdurrahman Paşa Fen Lisesi",
  "Kayseri Fen Lisesi",
  "Kırıkkale Fen Lisesi",
  "Kırklareli Fen Lisesi",
  "Kırşehir Prof. Dr. Ahi Evran Fen Lisesi",
  "Kilis Fen Lisesi",
  "Kocaeli Fen Lisesi",
  "Konya Meram Fen Lisesi",
  "Kütahya Nafi Güral Fen Lisesi",
  "Malatya Fen Lisesi",
  "Manisa Fen Lisesi",
  "Mardin Fen Lisesi",
  "Mersin Fen Lisesi",
  "Muş Fen Lisesi",
  "Nevşehir Fen Lisesi",
  "Niğde Fen Lisesi",
  "Ordu Fen Lisesi",
  "Osmaniye Fen Lisesi",
  "Rize Fen Lisesi",
  "Sakarya Cemil Meriç Fen Lisesi",
  "Siirt Fen Lisesi",
  "Sinop Fen Lisesi",
  "Sivas Fen Lisesi",
  "Şanlıurfa Fen Lisesi",
  "Şırnak Fen Lisesi",
  "Tekirdağ Ebru Nayim Fen Lisesi",
  "Tokat Gaziosmanpaşa Fen Lisesi",
  "Trabzon Fen Lisesi",
  "Tunceli Fen Lisesi",
  "Uşak Fen Lisesi",
  "Van Fen Lisesi",
  "Yalova Fen Lisesi",
  "Yozgat Fen Lisesi",
  "Zonguldak Fen Lisesi"
];
